CI housekeeping + support for Rails 8.1 (#210)
* fix CI badge and remove CodeClimate badge

* switch to Ubuntu 24.04 runners as 20.04 runners are EOL

* update to actions/checkout@v5 which uses NodeJS 24

* don't test with Rails 5.0 on Ruby 2.7

There's an error with bundler, and this combination is old enough
that it doesn't make sense to put effort in solving it.

NoMethodError: undefined method `name' for "rails_5_0.gemfile":String
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/resolver/spec_group.rb:65:in `eql?'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:607:in `block in create_conflict'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:606:in `each'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:606:in `create_conflict'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:700:in `attempt_to_filter_existing_spec'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:673:in `attempt_to_activate'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:254:in `process_topmost_state'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/resolver.rb:50:in `start'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/resolver.rb:22:in `resolve'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/definition.rb:258:in `resolve'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/definition.rb:170:in `specs'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/definition.rb:158:in `resolve_remotely!'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/cli/lock.rb:49:in `run'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/cli.rb:643:in `lock'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/bin/bundle:23:in `load'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/bin/bundle:23:in `<main>'

* fix CI failures with Rails 6.0, 6.1 and 7.0

* support Rails 8.1 with Ruby 3.2+

* Use bundler v2 in GitHub Actions

---------

Co-authored-by: Chris Griego <cgriego@gmail.com>